// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHPN9X0fKvOA9ttU-bt1toBFD1VucV70',
    appId: '1:161567192464:web:ac66f5a963a238f8046f15',
    messagingSenderId: '161567192464',
    projectId: 'blood-fit',
    authDomain: 'blood-fit.firebaseapp.com',
    storageBucket: 'blood-fit.firebasestorage.app',
    measurementId: 'G-NLPMW64YZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoHC2buvNAyGsFuKzElYPRLCQrgKbxPdA',
    appId: '1:161567192464:android:5afc3bbcbd36e2bd046f15',
    messagingSenderId: '161567192464',
    projectId: 'blood-fit',
    storageBucket: 'blood-fit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0_5qBDpxgibgsgrfa5MC6L5OeSLQ1ecc',
    appId: '1:161567192464:ios:bd4a16e16902f11f046f15',
    messagingSenderId: '161567192464',
    projectId: 'blood-fit',
    storageBucket: 'blood-fit.firebasestorage.app',
    iosBundleId: 'com.example.bloodfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdHPN9X0fKvOA9ttU-bt1toBFD1VucV70',
    appId: '1:161567192464:web:f5e1544ceb669d20046f15',
    messagingSenderId: '161567192464',
    projectId: 'blood-fit',
    authDomain: 'blood-fit.firebaseapp.com',
    storageBucket: 'blood-fit.firebasestorage.app',
    measurementId: 'G-YK74RFV581',
  );
}
